-- Migration: add missing admission and student fields for expanded admission form
-- Adds columns if they do not already exist so this can run on existing DB in-place.

-- ict_admissions additions
ALTER TABLE ict_admissions
  ADD COLUMN IF NOT EXISTS father_name VARCHAR(150),
  ADD COLUMN IF NOT EXISTS mother_name VARCHAR(150),
  ADD COLUMN IF NOT EXISTS guardian_name VARCHAR(150),
  ADD COLUMN IF NOT EXISTS emergency_contact VARCHAR(20),
  ADD COLUMN IF NOT EXISTS occupational_status VARCHAR(100),
  ADD COLUMN IF NOT EXISTS marital_status VARCHAR(50),
  ADD COLUMN IF NOT EXISTS nid_number VARCHAR(50),
  ADD COLUMN IF NOT EXISTS brc_number VARCHAR(50),
  ADD COLUMN IF NOT EXISTS current_address TEXT,
  ADD COLUMN IF NOT EXISTS current_district VARCHAR(150),
  ADD COLUMN IF NOT EXISTS current_police_station VARCHAR(150),
  ADD COLUMN IF NOT EXISTS current_union VARCHAR(150),
  ADD COLUMN IF NOT EXISTS current_post_office VARCHAR(150),
  ADD COLUMN IF NOT EXISTS current_post_code VARCHAR(20),
  ADD COLUMN IF NOT EXISTS current_village TEXT,
  ADD COLUMN IF NOT EXISTS permanent_address TEXT,
  ADD COLUMN IF NOT EXISTS permanent_district VARCHAR(150),
  ADD COLUMN IF NOT EXISTS permanent_police_station VARCHAR(150),
  ADD COLUMN IF NOT EXISTS permanent_union VARCHAR(150),
  ADD COLUMN IF NOT EXISTS permanent_post_office VARCHAR(150),
  ADD COLUMN IF NOT EXISTS permanent_post_code VARCHAR(20),
  ADD COLUMN IF NOT EXISTS permanent_village TEXT,
  ADD COLUMN IF NOT EXISTS religion VARCHAR(100),
  ADD COLUMN IF NOT EXISTS tribe VARCHAR(150),
  ADD COLUMN IF NOT EXISTS education VARCHAR(200),
  ADD COLUMN IF NOT EXISTS pwd BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS disability_type VARCHAR(100),
  ADD COLUMN IF NOT EXISTS total_family_members INT,
  ADD COLUMN IF NOT EXISTS source_of_income TEXT,
  ADD COLUMN IF NOT EXISTS number_of_earning_members INT,
  ADD COLUMN IF NOT EXISTS total_monthly_family_income NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS applicant_monthly_income NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS school_going_children INT,
  ADD COLUMN IF NOT EXISTS family_healthcare_source VARCHAR(200),
  ADD COLUMN IF NOT EXISTS recent_medical_visits INT,
  ADD COLUMN IF NOT EXISTS monthly_expenses NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS house_rent NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS monthly_meals NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS financial_status TEXT,
  ADD COLUMN IF NOT EXISTS has_savings BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS has_bank_account BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS social_security BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS training_institute VARCHAR(150),
  ADD COLUMN IF NOT EXISTS preferred_shift VARCHAR(50),
  ADD COLUMN IF NOT EXISTS registration_id VARCHAR(100),
  ADD COLUMN IF NOT EXISTS referral_source VARCHAR(200),
  ADD COLUMN IF NOT EXISTS prior_technical_skills BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS prior_skills_details TEXT,
  ADD COLUMN IF NOT EXISTS certification_status VARCHAR(200),
  ADD COLUMN IF NOT EXISTS training_duration VARCHAR(100),
  ADD COLUMN IF NOT EXISTS dropout_status BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS hours_attended INT,
  ADD COLUMN IF NOT EXISTS dropout_reason TEXT,
  ADD COLUMN IF NOT EXISTS competency BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS improvement_areas VARCHAR(200),
  ADD COLUMN IF NOT EXISTS trainee_signature TEXT,
  ADD COLUMN IF NOT EXISTS office_signature TEXT,
  ADD COLUMN IF NOT EXISTS profile_image TEXT;

-- ict_students additions
ALTER TABLE ict_students
  ADD COLUMN IF NOT EXISTS nid_number VARCHAR(50),
  ADD COLUMN IF NOT EXISTS brc_number VARCHAR(50),
  ADD COLUMN IF NOT EXISTS current_address TEXT,
  ADD COLUMN IF NOT EXISTS permanent_address TEXT,
  ADD COLUMN IF NOT EXISTS religion VARCHAR(50),
  ADD COLUMN IF NOT EXISTS tribe VARCHAR(100),
  ADD COLUMN IF NOT EXISTS education VARCHAR(150),
  ADD COLUMN IF NOT EXISTS pwd BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS disability_type VARCHAR(100),
  ADD COLUMN IF NOT EXISTS total_family_members INT,
  ADD COLUMN IF NOT EXISTS earning_members INT,
  ADD COLUMN IF NOT EXISTS total_monthly_income NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS applicant_monthly_income NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS school_going_children INT,
  ADD COLUMN IF NOT EXISTS family_healthcare_source VARCHAR(150),
  ADD COLUMN IF NOT EXISTS recent_medical_visits INT,
  ADD COLUMN IF NOT EXISTS monthly_expenses NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS house_rent NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS monthly_meals NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS has_savings BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS has_bank_account BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS social_security BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS training_institute VARCHAR(150),
  ADD COLUMN IF NOT EXISTS admission_date DATE,
  ADD COLUMN IF NOT EXISTS preferred_shift VARCHAR(50),
  ADD COLUMN IF NOT EXISTS registration_id VARCHAR(100),
  ADD COLUMN IF NOT EXISTS referral_source VARCHAR(200),
  ADD COLUMN IF NOT EXISTS prior_technical_skills BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS prior_skills_details TEXT,
  ADD COLUMN IF NOT EXISTS certification_status VARCHAR(100),
  ADD COLUMN IF NOT EXISTS training_duration VARCHAR(100),
  ADD COLUMN IF NOT EXISTS dropout_status BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS hours_attended INT,
  ADD COLUMN IF NOT EXISTS dropout_reason TEXT,
  ADD COLUMN IF NOT EXISTS competency BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS improvement_areas VARCHAR(200),
  ADD COLUMN IF NOT EXISTS remarks TEXT,
  ADD COLUMN IF NOT EXISTS admission_data JSONB;

-- student earnings table
CREATE TABLE IF NOT EXISTS ict_student_earnings (
  id SERIAL PRIMARY KEY,
  student_id INT NOT NULL REFERENCES ict_students(id) ON DELETE CASCADE,
  earning_source VARCHAR(200) NOT NULL,
  amount NUMERIC(12,2) NOT NULL,
  earning_date DATE NOT NULL DEFAULT CURRENT_DATE,
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes that might be useful
CREATE INDEX IF NOT EXISTS idx_ict_admissions_nid ON ict_admissions(nid_number);
CREATE INDEX IF NOT EXISTS idx_ict_students_nid ON ict_students(nid_number);
CREATE INDEX IF NOT EXISTS idx_ict_student_earnings_student_id ON ict_student_earnings(student_id);

-- end of migration
