CREATE TABLE IF NOT EXISTS ict_inventory (
  id SERIAL PRIMARY KEY,
  quantity NUMERIC(12,2) NOT NULL DEFAULT 0,
  unit VARCHAR(50),
  location VARCHAR(150),
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
